### ISSUE TITLE
AssetsReference类中资源引用管理只能管理一个资源引用bug

### ISSUE THREAD

**Issue by liang530** [Alex-Rachel/TEngine#101]
每次添加引用时，调用了_refAssetInfoList = new List<AssetsRefInfo>(); 重新生成了引用列表，前面添加的引用都被删除了
public AssetsReference Ref<T>(T source, IResourceManager resourceManager = null) where T : UnityEngine.Object
        {
            if (source == null)
            {
                throw new GameFrameworkException($"Source gameObject is null.");
            }

            _resourceManager = resourceManager;
            _refAssetInfoList = new List<AssetsRefInfo>();
            _refAssetInfoList.Add(new AssetsRefInfo(source));
            return this;
}

**Comment by Alex-Rachel** [comment]
@liang530 修复了 更新看下
