### ISSUE TITLE
无法更新包

### ISSUE THREAD

**Issue by JasonChocolate** [Alex-Rachel/TEngine#105]
![image](https://github.com/user-attachments/assets/8dc9186e-ba7d-4777-97b6-fa459c13c08a)
我安装Hybriclr后，点击BuildAssets And CopyTo AssemblyTextAssetPath，之后点击一键打包AsssetBundle，在编辑器使用联机模式能够正常更新，但是打出实体包，无法更新资源

**Comment by Alex-Rachel** [comment]
请打开Enable HybridCLR的宏定义。并检查dll.bytes是否打进包体。文档和csdn的教程都有说明
